import type {
  ReleaseGateConfigPanelBaselineColumnProps,
  ReleaseGateConfigPanelCoreTabProps,
  ReleaseGateConfigPanelModel,
  ReleaseGateConfigPanelParityTabProps,
  ReleaseGateConfigPanelPreviewTabProps,
} from "./releaseGateConfigPanelModel.types";

/** Narrows the full panel model to props for `ReleaseGateConfigPanelCoreTab` (single source with `ReleaseGateConfigPanelCoreTabProps`). */
export function pickReleaseGateConfigPanelCoreTabProps(
  m: ReleaseGateConfigPanelModel
): ReleaseGateConfigPanelCoreTabProps {
  const {
    REPLAY_PROVIDER_MODEL_LIBRARY,
    REPLAY_THRESHOLD_PRESETS,
    activeProviderTab,
    applySystemPromptToBody,
    editsLocked,
    failRateMax,
    flakyRateMax,
    handleResetSystemPrompt,
    hostedReplayCreditsExhausted,
    isSystemPromptOverridden,
    keyIssueBlocked,
    keyRegistrationMessage,
    missingProviderKeyDetails,
    canValidate,
    mutateProjectUserApiKeys,
    modelSource,
    modelOverrideEnabled,
    replayModelMode,
    newModel,
    normalizeGateThresholds,
    pinnedBadge,
    projectId,
    replayProvider,
    replayApiKey,
    replayUserApiKeyId,
    setReplayUserApiKeyId,
    projectUserApiKeysForUi,
    repeatRuns,
    requestSystemPrompt,
    runDataModel,
    runDataProvider,
    setActiveProviderTab,
    setFailRateMax,
    setFlakyRateMax,
    setReplayApiKey,
    setModelSource,
    setModelOverrideEnabled,
    setReplayModelMode,
    setNewModel,
    setReplayProvider,
    setRequestBody,
    setThresholdPreset,
    showCustomModelWarning,
    thresholdPreset,
    updateRequestNumberField,
  } = m;
  return {
    REPLAY_PROVIDER_MODEL_LIBRARY,
    REPLAY_THRESHOLD_PRESETS,
    activeProviderTab,
    applySystemPromptToBody,
    editsLocked,
    failRateMax,
    flakyRateMax,
    handleResetSystemPrompt,
    hostedReplayCreditsExhausted,
    isSystemPromptOverridden,
    keyIssueBlocked,
    keyRegistrationMessage,
    missingProviderKeyDetails,
    canValidate,
    mutateProjectUserApiKeys,
    modelSource,
    modelOverrideEnabled,
    replayModelMode,
    newModel,
    normalizeGateThresholds,
    pinnedBadge,
    projectId,
    replayProvider,
    replayApiKey,
    replayUserApiKeyId,
    setReplayUserApiKeyId,
    projectUserApiKeysForUi,
    repeatRuns,
    requestSystemPrompt,
    runDataModel,
    runDataProvider,
    setActiveProviderTab,
    setFailRateMax,
    setFlakyRateMax,
    setReplayApiKey,
    setModelSource,
    setModelOverrideEnabled,
    setReplayModelMode,
    setNewModel,
    setReplayProvider,
    setRequestBody,
    setThresholdPreset,
    showCustomModelWarning,
    thresholdPreset,
    updateRequestNumberField,
  };
}

export function pickReleaseGateConfigPanelParityTabProps(
  m: ReleaseGateConfigPanelModel
): ReleaseGateConfigPanelParityTabProps {
  const {
    addTool,
    baselineTimelineLoading,
    baselineToolTimelineRows,
    baselinePayload,
    candidateJsonValue,
    requestBody,
    updateRequestNumberField,
    bodyOverridesFileInputRef,
    bodyOverridesJsonError,
    bodyOverridesJsonValue,
    bodyOverridesSnapshotDraftRaw,
    bodyOverridesSnapshotJsonError,
    clearBodyOverrides,
    contextSummarySubtitle,
    editsLocked,
    getSnapshotParityLabel,
    handleRequestJsonBlur,
    handleResetJsonToBaseline,
    handleBodyOverridesJsonBlur,
    handleBodyOverridesSnapshotBlur,
    handleLoadToolContextFromSnapshots,
    hasAnyBodyOverridesContent,
    importBaselineToolSamples,
    isJsonModified,
    onBodyOverridesFileChange,
    onToolContextFileChange,
    overridesSummarySubtitle,
    parityOpenContext,
    parityOpenOverrides,
    parityOpenRawJson,
    parityOpenRecordedToolCalls,
    parityOpenTools,
    recordedCallsSummarySubtitle,
    removeTool,
    requestBodyOverridesBySnapshotId,
    requestJsonError,
    resetParityPerLogOverridesToBaseline,
    resetParitySharedOverridesToBaseline,
    resetParityToolContextToBaseline,
    resetParityToolsToBaseline,
    selectedSnapshotIdsForRun,
    setRequestJsonDraft,
    setBodyOverridesJsonDraft,
    setBodyOverridesSnapshotDraftRaw,
    setParityOpenContext,
    setParityOpenOverrides,
    setParityOpenRawJson,
    setParityOpenRecordedToolCalls,
    setParityOpenTools,
    setToolContextBySnapshotId,
    setToolContextGlobalText,
    setToolContextMode,
    setToolContextScope,
    snapshotIdForBaselineTimeline,
    toolContextBySnapshotId,
    toolContextFileInputRef,
    toolContextGlobalText,
    toolContextLoadBusy,
    toolContextMode,
    toolContextScope,
    toolsList,
    toolsSummarySubtitle,
    triggerBodyOverridesFilePick,
    triggerToolContextFilePick,
    updateTool,
  } = m;
  return {
    addTool,
    baselineTimelineLoading,
    baselineToolTimelineRows,
    baselinePayload,
    candidateJsonValue,
    requestBody,
    updateRequestNumberField,
    bodyOverridesFileInputRef,
    bodyOverridesJsonError,
    bodyOverridesJsonValue,
    bodyOverridesSnapshotDraftRaw,
    bodyOverridesSnapshotJsonError,
    clearBodyOverrides,
    contextSummarySubtitle,
    editsLocked,
    getSnapshotParityLabel,
    handleRequestJsonBlur,
    handleResetJsonToBaseline,
    handleBodyOverridesJsonBlur,
    handleBodyOverridesSnapshotBlur,
    handleLoadToolContextFromSnapshots,
    hasAnyBodyOverridesContent,
    importBaselineToolSamples,
    isJsonModified,
    onBodyOverridesFileChange,
    onToolContextFileChange,
    overridesSummarySubtitle,
    parityOpenContext,
    parityOpenOverrides,
    parityOpenRawJson,
    parityOpenRecordedToolCalls,
    parityOpenTools,
    recordedCallsSummarySubtitle,
    removeTool,
    requestBodyOverridesBySnapshotId,
    requestJsonError,
    resetParityPerLogOverridesToBaseline,
    resetParitySharedOverridesToBaseline,
    resetParityToolContextToBaseline,
    resetParityToolsToBaseline,
    selectedSnapshotIdsForRun,
    setRequestJsonDraft,
    setBodyOverridesJsonDraft,
    setBodyOverridesSnapshotDraftRaw,
    setParityOpenContext,
    setParityOpenOverrides,
    setParityOpenRawJson,
    setParityOpenRecordedToolCalls,
    setParityOpenTools,
    setToolContextBySnapshotId,
    setToolContextGlobalText,
    setToolContextMode,
    setToolContextScope,
    snapshotIdForBaselineTimeline,
    toolContextBySnapshotId,
    toolContextFileInputRef,
    toolContextGlobalText,
    toolContextLoadBusy,
    toolContextMode,
    toolContextScope,
    toolsList,
    toolsSummarySubtitle,
    triggerBodyOverridesFilePick,
    triggerToolContextFilePick,
    updateTool,
  };
}

export function pickReleaseGateConfigPanelPreviewTabProps(
  m: ReleaseGateConfigPanelModel
): ReleaseGateConfigPanelPreviewTabProps {
  const {
    candidateRequestOverview,
    finalCandidateJson,
    parityCandidateShapeNotes,
    parityEnvironmentNotes,
    representativeBaselineId,
    selectedBaselineCount,
    setShowExpandedCandidatePreview,
    toolsList,
    usingModel,
    usingProvider,
    validateOverridePreview,
  } = m;
  return {
    candidateRequestOverview,
    finalCandidateJson,
    parityCandidateShapeNotes,
    parityEnvironmentNotes,
    representativeBaselineId,
    selectedBaselineCount,
    setShowExpandedCandidatePreview,
    toolsList,
    usingModel,
    usingProvider,
    validateOverridePreview,
  };
}

export function pickReleaseGateConfigPanelBaselineColumnProps(
  m: ReleaseGateConfigPanelModel
): ReleaseGateConfigPanelBaselineColumnProps {
  const {
    autoRepresentativeBaselineSnapshotId,
    baselineConfigSummary,
    baselineRequestOverview,
    editsLocked,
    paritySummaryLines,
    representativeBaselineId,
    representativeBaselinePickerOptions,
    representativeBaselineUserSnapshotId,
    runDataModel,
    runDataProvider,
    runDataPrompt,
    selectedBaselineCount,
    selectedDataSummary,
    setRepresentativeBaselineUserSnapshotId,
    setShowRawBaseline,
  } = m;
  return {
    autoRepresentativeBaselineSnapshotId,
    baselineConfigSummary,
    baselineRequestOverview,
    editsLocked,
    paritySummaryLines,
    representativeBaselineId,
    representativeBaselinePickerOptions,
    representativeBaselineUserSnapshotId,
    runDataModel,
    runDataProvider,
    runDataPrompt,
    selectedBaselineCount,
    selectedDataSummary,
    setRepresentativeBaselineUserSnapshotId,
    setShowRawBaseline,
  };
}
