"use client";

import { useMemo } from "react";

import type { ReleaseGatePageContextValue } from "./releaseGatePageContext.types";
import {
  applySystemPromptToBody,
  normalizeGateThresholds,
  REPLAY_THRESHOLD_PRESETS,
  snapshotEvalFailed,
} from "./releaseGatePageContent.lib";

export const RELEASE_GATE_REPEAT_OPTIONS = [1, 10, 50, 100] as const;

export type UseReleaseGatePageContextValueParams = Omit<
  ReleaseGatePageContextValue,
  | "REPLAY_THRESHOLD_PRESETS"
  | "REPEAT_OPTIONS"
  | "snapshotEvalFailed"
  | "normalizeGateThresholds"
  | "applySystemPromptToBody"
>;

export function useReleaseGatePageContextValue(
  p: UseReleaseGatePageContextValueParams
): ReleaseGatePageContextValue {
  return useMemo(
    () => ({
      ...p,
      REPLAY_THRESHOLD_PRESETS,
      REPEAT_OPTIONS: RELEASE_GATE_REPEAT_OPTIONS,
      snapshotEvalFailed,
      normalizeGateThresholds,
      applySystemPromptToBody,
    }),
    [
      p.agentEvalData,
      p.agents,
      p.agentsLoaded,
      p.applyLoadedGlobalBodyOverrides,
      p.applyLoadedSnapshotBodyOverrides,
      p.autoRepresentativeBaselineSnapshotId,
      p.baselineConfigSummary,
      p.baselineDetailSnapshot,
      p.baselinePayload,
      p.baselineSeedSnapshot,
      p.baselineSnapshotsById,
      p.bodyOverridesJsonDraft,
      p.bodyOverridesJsonError,
      p.bodyOverridesSnapshotDraftRaw,
      p.bodyOverridesSnapshotJsonError,
      p.canRunValidate,
      p.clearBodyOverrides,
      p.resetParitySharedOverridesToBaseline,
      p.resetParityPerLogOverridesToBaseline,
      p.resetParityToolsToBaseline,
      p.resetParityToolContextToBaseline,
      p.configSourceLabel,
      p.dataSource,
      p.datasetSnapshots404,
      p.datasetSnapshotsError,
      p.datasetSnapshotsLoading,
      p.datasets,
      p.datasetsError,
      p.datasetsLoading,
      p.effectiveRepresentativeBaselineSnapshotId,
      p.expandedCaseIndex,
      p.expandedDatasetId,
      p.expandedDatasetSnapshots,
      p.expandedDatasetSnapshots404,
      p.expandedDatasetSnapshotsError,
      p.expandedDatasetSnapshotsLoading,
      p.expandedHistoryId,
      p.failRateMax,
      p.finalCandidateRequest,
      p.flakyRateMax,
      p.handleBodyOverridesJsonBlur,
      p.handleBodyOverridesSnapshotBlur,
      p.handleLoadToolContextFromSnapshots,
      p.handleRequestJsonBlur,
      p.historyDatePreset,
      p.historyItems,
      p.historyLimit,
      p.historyLoading,
      p.historyOffset,
      p.historyRefreshing,
      p.historyStatus,
      p.setHistoryDatePreset,
      p.setHistoryOffset,
      p.setHistoryStatus,
      p.setHistoryTraceId,
      p.historyTotal,
      p.historyTraceId,
      p.isHeavyRepeat,
      p.modelOverrideEnabled,
      p.mutateDatasetSnapshots,
      p.mutateDatasets,
      p.mutateExpandedDatasetSnapshots,
      p.mutateHistory,
      p.mutateRecentSnapshots,
      p.newModel,
      p.nodeBasePayload,
      p.onMapSelectAgent,
      p.openBaselineDetailSnapshot,
      p.orgId,
      p.project,
      p.projectId,
      p.recentSnapshots,
      p.recentSnapshotsError,
      p.recentSnapshotsLoading,
      p.recentSnapshotsTotalAvailable,
      p.repeatDropdownOpen,
      p.repeatRuns,
      p.replayProvider,
      p.REPLAY_PROVIDER_MODEL_LIBRARY,
      p.representativeBaselinePickerOptions,
      p.representativeBaselineUserSnapshotId,
      p.requestBody,
      p.requestBodyJson,
      p.requestBodyOverrides,
      p.requestBodyOverridesBySnapshotId,
      p.requestBodyOverridesJson,
      p.requestJsonDraft,
      p.requestJsonError,
      p.requestSystemPrompt,
      p.runDataModel,
      p.runDataPrompt,
      p.runDataProvider,
      p.runDatasetIds,
      p.runEvalElements,
      p.runSnapshotIds,
      p.selectedAgent,
      p.selectedAttempt,
      p.selectedBaselineCount,
      p.selectedDataSummary,
      p.selectedRunId,
      p.selectedRunReport,
      p.selectedRunReportError,
      p.selectedRunReportLoading,
      p.selectedSnapshotIdsForRun,
      p.tab,
      p.thresholdPreset,
      p.toolContextBySnapshotId,
      p.toolContextGlobalText,
      p.toolContextLoadBusy,
      p.toolContextMode,
      p.toolContextScope,
      p.toolsList,
      p.validateOverridePreview,
    ]
  );
}
