"""Add is_panic_mode to Project

Revision ID: 10088e892baa
Revises: 896063a36393
Create Date: 2026-01-24 21:25:51.512146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10088e892baa'
down_revision = '896063a36393'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_panic_mode', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_panic_mode')
    # ### end Alembic commands ###
