"""restore_test_lab_tables

Revision ID: 5e5a8559f4d4
Revises: 67fc79a64a2d
Create Date: 2026-02-15 21:55:29.962920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e5a8559f4d4'
down_revision = '67fc79a64a2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)

    # 20260205_phase1_schema_alignment may have already created these (merge graph).
    if not insp.has_table("agent_display_settings"):
        op.create_table('agent_display_settings',
        sa.Column('id', sa.String(length=255), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('system_prompt_hash', sa.String(length=64), nullable=False),
        sa.Column('display_name', sa.String(length=100), nullable=True),
        sa.Column('node_type', sa.String(length=50), server_default='agentCard', nullable=True),
        sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('system_prompt_hash', name='uq_agent_display_settings_system_prompt_hash')
        )
        op.create_index(op.f('ix_agent_display_settings_created_at'), 'agent_display_settings', ['created_at'], unique=False)
        op.create_index(op.f('ix_agent_display_settings_id'), 'agent_display_settings', ['id'], unique=False)
        op.create_index(op.f('ix_agent_display_settings_project_id'), 'agent_display_settings', ['project_id'], unique=False)
        op.create_table('live_view_connections',
        sa.Column('id', sa.String(length=255), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('source_agent_name', sa.String(length=100), nullable=False),
        sa.Column('target_agent_name', sa.String(length=100), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_live_view_connections_created_at'), 'live_view_connections', ['created_at'], unique=False)
        op.create_index(op.f('ix_live_view_connections_id'), 'live_view_connections', ['id'], unique=False)
        op.create_index(op.f('ix_live_view_connections_project_id'), 'live_view_connections', ['project_id'], unique=False)
        op.create_table('replay_runs',
        sa.Column('id', sa.String(length=255), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('run_type', sa.String(length=20), nullable=True),
        sa.Column('target_model', sa.String(length=100), nullable=True),
        sa.Column('snapshot_count', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('total_latency_ms', sa.BigInteger(), nullable=True),
        sa.Column('total_cost', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_replay_runs_id'), 'replay_runs', ['id'], unique=False)
        op.create_index(op.f('ix_replay_runs_project_id'), 'replay_runs', ['project_id'], unique=False)
        op.create_table('signal_configs',
        sa.Column('id', sa.String(length=255), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('signal_type', sa.String(length=50), nullable=False),
        sa.Column('params', sa.JSON(), nullable=True),
        sa.Column('severity', sa.String(length=20), nullable=True),
        sa.Column('enabled', sa.Boolean(), server_default='true', nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_signal_configs_created_at'), 'signal_configs', ['created_at'], unique=False)
        op.create_index(op.f('ix_signal_configs_id'), 'signal_configs', ['id'], unique=False)
        op.create_index(op.f('ix_signal_configs_project_id'), 'signal_configs', ['project_id'], unique=False)
        op.create_table('test_lab_canvases',
        sa.Column('id', sa.String(length=255), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('boxes', sa.JSON(), nullable=True),
        sa.Column('connections', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_test_lab_canvases_created_at'), 'test_lab_canvases', ['created_at'], unique=False)
        op.create_index(op.f('ix_test_lab_canvases_id'), 'test_lab_canvases', ['id'], unique=False)
        op.create_index(op.f('ix_test_lab_canvases_project_id'), 'test_lab_canvases', ['project_id'], unique=False)
        op.create_table('test_runs',
        sa.Column('id', sa.String(length=255), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('test_type', sa.String(length=50), nullable=False),
        sa.Column('agent_config', sa.JSON(), nullable=True),
        sa.Column('signal_config', sa.JSON(), nullable=True),
        sa.Column('total_count', sa.Integer(), nullable=True),
        sa.Column('pass_count', sa.Integer(), nullable=True),
        sa.Column('fail_count', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_test_runs_created_at'), 'test_runs', ['created_at'], unique=False)
        op.create_index(op.f('ix_test_runs_id'), 'test_runs', ['id'], unique=False)
        op.create_index(op.f('ix_test_runs_project_id'), 'test_runs', ['project_id'], unique=False)
        op.create_table('signal_detections',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('snapshot_id', sa.Integer(), nullable=True),
        sa.Column('signal_type', sa.String(length=50), nullable=False),
        sa.Column('severity', sa.String(length=20), nullable=True),
        sa.Column('detected', sa.Boolean(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('custom_signal_name', sa.String(length=255), nullable=True),
        sa.Column('custom_signal_rule', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_signal_detections_created_at'), 'signal_detections', ['created_at'], unique=False)
        op.create_index(op.f('ix_signal_detections_id'), 'signal_detections', ['id'], unique=False)
        op.create_index(op.f('ix_signal_detections_project_id'), 'signal_detections', ['project_id'], unique=False)
        op.create_index(op.f('ix_signal_detections_signal_type'), 'signal_detections', ['signal_type'], unique=False)
        op.create_index(op.f('ix_signal_detections_snapshot_id'), 'signal_detections', ['snapshot_id'], unique=False)
        op.create_table('test_results',
        sa.Column('id', sa.String(length=255), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('agent_id', sa.String(length=100), nullable=True),
        sa.Column('test_run_id', sa.String(length=255), nullable=True),
        sa.Column('step_order', sa.Integer(), nullable=True),
        sa.Column('parent_step_id', sa.String(length=255), nullable=True),
        sa.Column('is_parallel', sa.Boolean(), server_default='false', nullable=True),
        sa.Column('input', sa.Text(), nullable=True),
        sa.Column('system_prompt', sa.Text(), nullable=True),
        sa.Column('model', sa.String(length=100), nullable=True),
        sa.Column('response', sa.Text(), nullable=True),
        sa.Column('latency_ms', sa.Integer(), nullable=True),
        sa.Column('tokens_used', sa.Integer(), nullable=True),
        sa.Column('cost', sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column('signal_result', sa.JSON(), nullable=True),
        sa.Column('is_worst', sa.Boolean(), server_default='false', nullable=True),
        sa.Column('worst_status', sa.String(length=20), nullable=True),
        sa.Column('baseline_snapshot_id', sa.Integer(), nullable=True),
        sa.Column('baseline_response', sa.Text(), nullable=True),
        sa.Column('source', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['baseline_snapshot_id'], ['snapshots.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_test_results_agent_id'), 'test_results', ['agent_id'], unique=False)
        op.create_index(op.f('ix_test_results_created_at'), 'test_results', ['created_at'], unique=False)
        op.create_index(op.f('ix_test_results_id'), 'test_results', ['id'], unique=False)
        op.create_index(op.f('ix_test_results_project_id'), 'test_results', ['project_id'], unique=False)
        op.create_index(op.f('ix_test_results_test_run_id'), 'test_results', ['test_run_id'], unique=False)
    op.drop_index(op.f('ix_shadow_comparisons_created_at'), table_name='shadow_comparisons')
    op.drop_index(op.f('ix_shadow_comparisons_id'), table_name='shadow_comparisons')
    op.drop_index(op.f('ix_shadow_comparisons_primary_api_call_id'), table_name='shadow_comparisons')
    op.drop_index(op.f('ix_shadow_comparisons_project_id'), table_name='shadow_comparisons')
    op.drop_index(op.f('ix_shadow_comparisons_shadow_api_call_id'), table_name='shadow_comparisons')
    op.drop_table('shadow_comparisons')
    op.drop_constraint(op.f('activity_logs_project_id_fkey'), 'activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'activity_logs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('alerts', sa.Column('description', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_constraint(op.f('alerts_project_id_fkey'), 'alerts', type_='foreignkey')
    op.drop_constraint(op.f('alerts_resolved_by_fkey'), 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('alerts', 'sent_at')
    op.drop_column('alerts', 'alert_data')
    op.drop_column('alerts', 'resolved_by')
    op.drop_column('alerts', 'notification_channels')
    op.drop_column('alerts', 'message')
    op.drop_column('alerts', 'is_sent')
    op.add_column('api_calls', sa.Column('request_content', sa.Text(), nullable=True))
    op.add_column('api_calls', sa.Column('response_content', sa.Text(), nullable=True))
    op.add_column('api_calls', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('api_calls', sa.Column('cost', sa.Float(), nullable=True))
    op.alter_column('api_calls', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('api_calls', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('api_calls', 'latency_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('idx_chain_id'), table_name='api_calls')
    op.drop_index(op.f('idx_project_created'), table_name='api_calls')
    op.drop_index(op.f('idx_provider_model'), table_name='api_calls')
    op.drop_index(op.f('ix_api_calls_agent_name'), table_name='api_calls')
    op.drop_index(op.f('ix_api_calls_chain_id'), table_name='api_calls')
    op.drop_index(op.f('ix_api_calls_model'), table_name='api_calls')
    op.drop_index(op.f('ix_api_calls_provider'), table_name='api_calls')
    op.drop_constraint(op.f('api_calls_project_id_fkey'), 'api_calls', type_='foreignkey')
    op.create_foreign_key(None, 'api_calls', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('api_calls', 'chain_id')
    op.drop_column('api_calls', 'response_tokens')
    op.drop_column('api_calls', 'request_prompt')
    op.drop_column('api_calls', 'error_message')
    op.drop_column('api_calls', 'response_data')
    op.drop_column('api_calls', 'request_tokens')
    op.drop_column('api_calls', 'request_data')
    op.drop_column('api_calls', 'response_text')
    op.add_column('drift_detections', sa.Column('model_name', sa.String(length=100), nullable=True))
    op.add_column('drift_detections', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('ix_drift_detections_agent_name'), table_name='drift_detections')
    op.drop_index(op.f('ix_drift_detections_detected_at'), table_name='drift_detections')
    op.drop_index(op.f('ix_drift_detections_detection_type'), table_name='drift_detections')
    op.drop_index(op.f('ix_drift_detections_model'), table_name='drift_detections')
    op.create_index(op.f('ix_drift_detections_created_at'), 'drift_detections', ['created_at'], unique=False)
    op.drop_constraint(op.f('drift_detections_project_id_fkey'), 'drift_detections', type_='foreignkey')
    op.create_foreign_key(None, 'drift_detections', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('drift_detections', 'model')
    op.drop_column('drift_detections', 'baseline_period_start')
    op.drop_column('drift_detections', 'agent_name')
    op.drop_column('drift_detections', 'detection_type')
    op.drop_column('drift_detections', 'current_value')
    op.drop_column('drift_detections', 'change_percentage')
    op.drop_column('drift_detections', 'affected_fields')
    op.drop_column('drift_detections', 'detection_details')
    op.drop_column('drift_detections', 'baseline_value')
    op.drop_column('drift_detections', 'detected_at')
    op.drop_column('drift_detections', 'severity')
    op.drop_column('drift_detections', 'baseline_period_end')
    op.alter_column('evaluation_rubrics', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    # core_legacy / 9d03 may already have created these indexes on empty-DB CI.
    _rubric_ix = {idx["name"] for idx in sa.inspect(bind).get_indexes("evaluation_rubrics")}
    _nm_ca = op.f("ix_evaluation_rubrics_created_at")
    _nm_pi = op.f("ix_evaluation_rubrics_project_id")
    if _nm_ca not in _rubric_ix:
        op.create_index(_nm_ca, "evaluation_rubrics", ["created_at"], unique=False)
    if _nm_pi not in _rubric_ix:
        op.create_index(_nm_pi, "evaluation_rubrics", ["project_id"], unique=False)
    op.drop_column('evaluation_rubrics', 'min_score')
    op.drop_column('evaluation_rubrics', 'max_score')
    op.drop_column('evaluation_rubrics', 'criteria_prompt')
    op.drop_column('evaluation_rubrics', 'updated_at')
    op.add_column('firewall_rules', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True))
    op.add_column('firewall_rules', sa.Column('priority', sa.Integer(), nullable=True))
    op.alter_column('firewall_rules', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('firewall_rules', 'action',
               existing_type=postgresql.ENUM('BLOCK', 'WARN', 'LOG', name='firewallaction'),
               nullable=True)
    op.alter_column('firewall_rules', 'severity',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='firewallseverity'),
               nullable=True)
    op.drop_index(op.f('ix_firewall_rules_enabled'), table_name='firewall_rules')
    op.drop_index(op.f('ix_firewall_rules_rule_type'), table_name='firewall_rules')
    op.create_index(op.f('ix_firewall_rules_created_at'), 'firewall_rules', ['created_at'], unique=False)
    op.drop_column('firewall_rules', 'config')
    op.drop_column('firewall_rules', 'updated_at')
    op.drop_column('firewall_rules', 'enabled')
    op.drop_column('firewall_rules', 'pattern_type')
    op.drop_column('firewall_rules', 'description')
    op.add_column('judge_feedback', sa.Column('snapshot_id', sa.Integer(), nullable=True))
    op.add_column('judge_feedback', sa.Column('judge_id', sa.Integer(), nullable=True))
    op.add_column('judge_feedback', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('judge_feedback', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_judge_feedback_evaluation_id'), table_name='judge_feedback')
    op.drop_constraint(op.f('judge_feedback_evaluation_id_fkey'), 'judge_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'judge_feedback', 'users', ['judge_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'judge_feedback', 'snapshots', ['snapshot_id'], ['id'], ondelete='CASCADE')
    op.drop_column('judge_feedback', 'judge_score')
    op.drop_column('judge_feedback', 'human_score')
    op.drop_column('judge_feedback', 'updated_at')
    op.drop_column('judge_feedback', 'metadata')
    op.drop_column('judge_feedback', 'correction_reason')
    op.drop_column('judge_feedback', 'evaluation_id')
    op.drop_column('judge_feedback', 'alignment_score')
    op.add_column('notification_settings', sa.Column('email_alerts', sa.Boolean(), server_default='true', nullable=True))
    op.add_column('notification_settings', sa.Column('slack_alerts', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('notification_settings', sa.Column('discord_alerts', sa.Boolean(), server_default='false', nullable=True))
    op.alter_column('notification_settings', 'slack_webhook_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('notification_settings', 'discord_webhook_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_index(op.f('ix_notification_settings_user_id'), table_name='notification_settings')
    op.create_unique_constraint(None, 'notification_settings', ['user_id'])
    op.drop_constraint(op.f('notification_settings_user_id_fkey'), 'notification_settings', type_='foreignkey')
    op.create_foreign_key(None, 'notification_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notification_settings', 'created_at')
    op.drop_column('notification_settings', 'email_quality_drop')
    op.drop_column('notification_settings', 'email_cost_anomaly')
    op.drop_column('notification_settings', 'in_app_cost_anomaly')
    op.drop_column('notification_settings', 'email_drift')
    op.drop_column('notification_settings', 'slack_enabled')
    op.drop_column('notification_settings', 'discord_enabled')
    op.drop_column('notification_settings', 'in_app_drift')
    op.drop_column('notification_settings', 'in_app_quality_drop')
    op.drop_index(op.f('idx_org_member'), table_name='organization_members')
    op.drop_index(op.f('idx_org_member_role'), table_name='organization_members')
    op.drop_constraint(op.f('uq_org_user'), 'organization_members', type_='unique')
    op.drop_constraint(op.f('organization_members_user_id_fkey'), 'organization_members', type_='foreignkey')
    op.drop_constraint(op.f('organization_members_invited_by_fkey'), 'organization_members', type_='foreignkey')
    op.drop_constraint(op.f('organization_members_organization_id_fkey'), 'organization_members', type_='foreignkey')
    op.create_foreign_key(None, 'organization_members', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'organization_members', 'users', ['user_id'], ['id'])
    op.drop_column('organization_members', 'invited_at')
    op.drop_column('organization_members', 'invited_by')
    op.drop_column('organization_members', 'joined_at')
    op.drop_column('organization_members', 'updated_at')
    op.drop_index(op.f('idx_org_owner'), table_name='organizations')
    op.drop_index(op.f('idx_org_plan'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_paddle_customer_id'), table_name='organizations')
    op.create_index(op.f('ix_organizations_paddle_customer_id'), 'organizations', ['paddle_customer_id'], unique=False)
    op.drop_index(op.f('ix_organizations_paddle_subscription_id'), table_name='organizations')
    op.create_index(op.f('ix_organizations_paddle_subscription_id'), 'organizations', ['paddle_subscription_id'], unique=False)
    op.add_column('pii_patterns', sa.Column('entity_type', sa.String(length=50), nullable=True))
    op.alter_column('pii_patterns', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_pii_patterns_project_id'), table_name='pii_patterns')
    op.drop_constraint(op.f('pii_patterns_project_id_fkey'), 'pii_patterns', type_='foreignkey')
    op.drop_column('pii_patterns', 'project_id')
    op.drop_column('pii_patterns', 'replacement')
    op.drop_column('pii_patterns', 'updated_at')
    op.add_column('project_notification_settings', sa.Column('slack_channel', sa.String(length=100), nullable=True))
    op.alter_column('project_notification_settings', 'email_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('project_notification_settings', 'slack_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_project_notification_settings_project_id'), table_name='project_notification_settings')
    op.drop_index(op.f('ix_project_notification_settings_user_id'), table_name='project_notification_settings')
    op.drop_constraint(op.f('uq_project_notification_settings_project_user'), 'project_notification_settings', type_='unique')
    op.create_unique_constraint(None, 'project_notification_settings', ['project_id'])
    op.drop_constraint(op.f('project_notification_settings_user_id_fkey'), 'project_notification_settings', type_='foreignkey')
    op.drop_column('project_notification_settings', 'discord_webhook_url')
    op.drop_column('project_notification_settings', 'created_at')
    op.drop_column('project_notification_settings', 'severity_threshold')
    op.drop_column('project_notification_settings', 'drift_threshold')
    op.drop_column('project_notification_settings', 'quality_score_threshold')
    op.drop_column('project_notification_settings', 'user_id')
    op.drop_column('project_notification_settings', 'alert_types')
    op.drop_column('project_notification_settings', 'slack_webhook_url')
    op.drop_column('project_notification_settings', 'min_interval_minutes')
    op.drop_column('project_notification_settings', 'discord_enabled')
    op.drop_column('project_notification_settings', 'error_rate_threshold')
    # add_organizations uses index=True → ix_projects_organization_id, not idx_*.
    _proj_ix = {idx["name"] for idx in sa.inspect(bind).get_indexes("projects")}
    _drop_org = op.f("idx_projects_organization_id")
    if _drop_org in _proj_ix:
        op.drop_index(_drop_org, table_name="projects")
        _proj_ix = {idx["name"] for idx in sa.inspect(bind).get_indexes("projects")}
    _ix_org = op.f("ix_projects_organization_id")
    if _ix_org not in _proj_ix:
        op.create_index(_ix_org, "projects", ["organization_id"], unique=False)
    op.drop_column('projects', 'shadow_routing_config')
    op.add_column('public_benchmarks', sa.Column('version', sa.String(length=20), nullable=True))
    op.add_column('public_benchmarks', sa.Column('data', sa.JSON(), nullable=False, server_default='{}'))
    op.alter_column('public_benchmarks', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_public_benchmark_category_approved'), table_name='public_benchmarks')
    op.drop_index(op.f('ix_public_benchmark_featured_approved'), table_name='public_benchmarks')
    op.drop_index(op.f('ix_public_benchmarks_author_id'), table_name='public_benchmarks')
    op.drop_index(op.f('ix_public_benchmarks_benchmark_type'), table_name='public_benchmarks')
    op.drop_index(op.f('ix_public_benchmarks_category'), table_name='public_benchmarks')
    op.drop_index(op.f('ix_public_benchmarks_created_at'), table_name='public_benchmarks')
    op.drop_index(op.f('ix_public_benchmarks_is_approved'), table_name='public_benchmarks')
    op.drop_index(op.f('ix_public_benchmarks_is_featured'), table_name='public_benchmarks')
    op.drop_constraint(op.f('public_benchmarks_author_id_fkey'), 'public_benchmarks', type_='foreignkey')
    op.drop_column('public_benchmarks', 'updated_at')
    op.drop_column('public_benchmarks', 'author_id')
    op.drop_column('public_benchmarks', 'is_approved')
    op.drop_column('public_benchmarks', 'category')
    op.drop_column('public_benchmarks', 'benchmark_data')
    op.drop_column('public_benchmarks', 'test_cases_count')
    op.drop_column('public_benchmarks', 'description')
    op.drop_column('public_benchmarks', 'view_count')
    op.drop_column('public_benchmarks', 'is_featured')
    op.drop_column('public_benchmarks', 'benchmark_type')
    op.drop_column('public_benchmarks', 'tags')
    op.add_column('quality_scores', sa.Column('score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('quality_scores', sa.Column('metric_name', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_quality_scores_api_call_id'), table_name='quality_scores')
    op.drop_constraint(op.f('quality_scores_api_call_id_fkey'), 'quality_scores', type_='foreignkey')
    op.drop_constraint(op.f('quality_scores_project_id_fkey'), 'quality_scores', type_='foreignkey')
    op.create_foreign_key(None, 'quality_scores', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('quality_scores', 'length_acceptable')
    op.drop_column('quality_scores', 'required_fields_present')
    op.drop_column('quality_scores', 'evaluation_details')
    op.drop_column('quality_scores', 'format_valid')
    op.drop_column('quality_scores', 'violations')
    op.drop_column('quality_scores', 'api_call_id')
    op.drop_column('quality_scores', 'json_valid')
    op.drop_column('quality_scores', 'tone_score')
    op.drop_column('quality_scores', 'semantic_consistency_score')
    op.drop_column('quality_scores', 'coherence_score')
    op.drop_column('quality_scores', 'overall_score')
    op.add_column('rule_market', sa.Column('config_json', sa.Text(), nullable=False, server_default='{}'))
    op.add_column('rule_market', sa.Column('author', sa.String(length=100), nullable=True))
    op.add_column('rule_market', sa.Column('downloads', sa.Integer(), nullable=True))
    op.alter_column('rule_market', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_rule_market_author_id'), table_name='rule_market')
    op.drop_index(op.f('ix_rule_market_category'), table_name='rule_market')
    op.drop_index(op.f('ix_rule_market_category_approved'), table_name='rule_market')
    op.drop_index(op.f('ix_rule_market_created_at'), table_name='rule_market')
    op.drop_index(op.f('ix_rule_market_featured_approved'), table_name='rule_market')
    op.drop_index(op.f('ix_rule_market_is_approved'), table_name='rule_market')
    op.drop_index(op.f('ix_rule_market_is_featured'), table_name='rule_market')
    op.drop_index(op.f('ix_rule_market_rule_type'), table_name='rule_market')
    op.drop_constraint(op.f('rule_market_author_id_fkey'), 'rule_market', type_='foreignkey')
    op.drop_column('rule_market', 'rating_count')
    op.drop_column('rule_market', 'updated_at')
    op.drop_column('rule_market', 'download_count')
    op.drop_column('rule_market', 'pattern')
    op.drop_column('rule_market', 'author_id')
    op.drop_column('rule_market', 'is_approved')
    op.drop_column('rule_market', 'category')
    op.drop_column('rule_market', 'pattern_type')
    op.drop_column('rule_market', 'is_featured')
    op.drop_column('rule_market', 'tags')
    op.drop_column('rule_market', 'rating')
    op.add_column('shared_results', sa.Column('test_run_id', sa.String(length=255), nullable=True))
    op.add_column('shared_results', sa.Column('share_token', sa.String(length=255), nullable=True))
    op.add_column('shared_results', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('shared_results', sa.Column('settings', sa.JSON(), nullable=True))
    op.alter_column('shared_results', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('idx_shared_result_project'), table_name='shared_results')
    op.drop_index(op.f('idx_shared_result_token'), table_name='shared_results')
    op.drop_index(op.f('ix_shared_results_created_at'), table_name='shared_results')
    op.drop_index(op.f('ix_shared_results_created_by'), table_name='shared_results')
    op.drop_index(op.f('ix_shared_results_result_type'), table_name='shared_results')
    op.drop_index(op.f('ix_shared_results_token'), table_name='shared_results')
    op.create_index(op.f('ix_shared_results_share_token'), 'shared_results', ['share_token'], unique=True)
    op.drop_constraint(op.f('shared_results_created_by_fkey'), 'shared_results', type_='foreignkey')
    op.create_foreign_key(None, 'shared_results', 'test_runs', ['test_run_id'], ['id'], ondelete='CASCADE')
    op.drop_column('shared_results', 'result_id')
    op.drop_column('shared_results', 'read_only')
    op.drop_column('shared_results', 'created_by')
    op.drop_column('shared_results', 'token')
    op.drop_column('shared_results', 'result_type')
    op.drop_column('shared_results', 'result_data')
    op.add_column('snapshots', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('snapshots', sa.Column('agent_id', sa.String(length=100), nullable=True))
    op.add_column('snapshots', sa.Column('parent_span_id', sa.String(length=255), nullable=True))
    op.add_column('snapshots', sa.Column('span_order', sa.Integer(), nullable=True))
    op.add_column('snapshots', sa.Column('is_parallel', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('snapshots', sa.Column('model_settings', sa.JSON(), nullable=True))
    op.add_column('snapshots', sa.Column('system_prompt', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('user_message', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('response', sa.Text(), nullable=True))
    op.add_column('snapshots', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('snapshots', sa.Column('tokens_used', sa.Integer(), nullable=True))
    op.add_column('snapshots', sa.Column('cost', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('snapshots', sa.Column('signal_result', sa.JSON(), nullable=True))
    op.add_column('snapshots', sa.Column('is_worst', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('snapshots', sa.Column('worst_status', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_snapshots_agent_id'), 'snapshots', ['agent_id'], unique=False)
    op.create_index(op.f('ix_snapshots_project_id'), 'snapshots', ['project_id'], unique=False)
    op.create_foreign_key(None, 'snapshots', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('subscriptions', 'current_period_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('idx_subscription_plan'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscription_user_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_paddle_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_paddle_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.create_unique_constraint(None, 'subscriptions', ['user_id'])
    op.drop_constraint(op.f('subscriptions_user_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subscriptions', 'cancel_at_period_end')
    op.drop_column('subscriptions', 'paddle_customer_id')
    op.drop_column('subscriptions', 'price_per_month')
    op.drop_column('subscriptions', 'plan_type')
    op.drop_column('subscriptions', 'trial_end')
    op.drop_column('subscriptions', 'current_period_start')
    op.drop_column('subscriptions', 'paddle_subscription_id')
    op.add_column('usage', sa.Column('metric_name', sa.String(length=50), nullable=False, server_default='generic_usage'))
    op.add_column('usage', sa.Column('quantity', sa.BigInteger(), nullable=True))
    op.add_column('usage', sa.Column('unit', sa.String(length=20), nullable=True))
    op.add_column('usage', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('usage', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('idx_usage_project_metric'), table_name='usage')
    op.drop_index(op.f('idx_usage_user_metric'), table_name='usage')
    op.drop_index(op.f('ix_usage_project_id'), table_name='usage')
    op.drop_index(op.f('ix_usage_user_id'), table_name='usage')
    op.create_index(op.f('ix_usage_timestamp'), 'usage', ['timestamp'], unique=False)
    op.drop_constraint(op.f('usage_user_id_fkey'), 'usage', type_='foreignkey')
    op.drop_constraint(op.f('usage_project_id_fkey'), 'usage', type_='foreignkey')
    op.create_foreign_key(None, 'usage', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'usage', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('usage', 'created_at')
    op.drop_column('usage', 'limit')
    op.drop_column('usage', 'period_end')
    op.drop_column('usage', 'updated_at')
    op.drop_column('usage', 'current_usage')
    op.drop_column('usage', 'period_start')
    op.drop_column('usage', 'metric_type')
    op.add_column('user_agreements', sa.Column('version', sa.String(length=20), nullable=True))
    op.drop_constraint(op.f('user_agreements_user_id_fkey'), 'user_agreements', type_='foreignkey')
    op.create_foreign_key(None, 'user_agreements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('webhooks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('webhooks', 'url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('webhooks', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('webhooks', 'events',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               nullable=True)
    op.drop_index(op.f('idx_webhook_project_active'), table_name='webhooks')
    op.drop_index(op.f('idx_webhook_user_active'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_created_at'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_project_id'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_user_id'), table_name='webhooks')
    op.drop_constraint(op.f('webhooks_project_id_fkey'), 'webhooks', type_='foreignkey')
    op.drop_constraint(op.f('webhooks_user_id_fkey'), 'webhooks', type_='foreignkey')
    op.create_foreign_key(None, 'webhooks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'webhooks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('webhooks', 'failure_count')
    op.drop_column('webhooks', 'last_error')
    op.drop_column('webhooks', 'last_triggered_at')
    op.drop_column('webhooks', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhooks', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('webhooks', sa.Column('last_triggered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('webhooks', sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('webhooks', sa.Column('failure_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'webhooks', type_='foreignkey')
    op.drop_constraint(None, 'webhooks', type_='foreignkey')
    op.create_foreign_key(op.f('webhooks_user_id_fkey'), 'webhooks', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('webhooks_project_id_fkey'), 'webhooks', 'projects', ['project_id'], ['id'])
    op.create_index(op.f('ix_webhooks_user_id'), 'webhooks', ['user_id'], unique=False)
    op.create_index(op.f('ix_webhooks_project_id'), 'webhooks', ['project_id'], unique=False)
    op.create_index(op.f('ix_webhooks_created_at'), 'webhooks', ['created_at'], unique=False)
    op.create_index(op.f('idx_webhook_user_active'), 'webhooks', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('idx_webhook_project_active'), 'webhooks', ['project_id', 'is_active'], unique=False)
    op.alter_column('webhooks', 'events',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('webhooks', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('webhooks', 'url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('webhooks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'user_agreements', type_='foreignkey')
    op.create_foreign_key(op.f('user_agreements_user_id_fkey'), 'user_agreements', 'users', ['user_id'], ['id'])
    op.drop_column('user_agreements', 'version')
    op.add_column('usage', sa.Column('metric_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('usage', sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('usage', sa.Column('current_usage', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('usage', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('usage', sa.Column('period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('usage', sa.Column('limit', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('usage', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usage', type_='foreignkey')
    op.drop_constraint(None, 'usage', type_='foreignkey')
    op.create_foreign_key(op.f('usage_project_id_fkey'), 'usage', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('usage_user_id_fkey'), 'usage', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_usage_timestamp'), table_name='usage')
    op.create_index(op.f('ix_usage_user_id'), 'usage', ['user_id'], unique=False)
    op.create_index(op.f('ix_usage_project_id'), 'usage', ['project_id'], unique=False)
    op.create_index(op.f('idx_usage_user_metric'), 'usage', ['user_id', 'metric_type', 'period_start'], unique=False)
    op.create_index(op.f('idx_usage_project_metric'), 'usage', ['project_id', 'metric_type', 'period_start'], unique=False)
    op.alter_column('usage', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('usage', 'timestamp')
    op.drop_column('usage', 'unit')
    op.drop_column('usage', 'quantity')
    op.drop_column('usage', 'metric_name')
    op.add_column('subscriptions', sa.Column('paddle_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('current_period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, server_default=sa.func.now()))
    op.add_column('subscriptions', sa.Column('trial_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('plan_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False, server_default='free'))
    op.add_column('subscriptions', sa.Column('price_per_month', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('paddle_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('cancel_at_period_end', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_user_id_fkey'), 'subscriptions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_paddle_subscription_id'), 'subscriptions', ['paddle_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_paddle_customer_id'), 'subscriptions', ['paddle_customer_id'], unique=False)
    op.create_index(op.f('idx_subscription_user_status'), 'subscriptions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_subscription_plan'), 'subscriptions', ['plan_type', 'status'], unique=False)
    op.alter_column('subscriptions', 'current_period_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(None, 'snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_snapshots_project_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_agent_id'), table_name='snapshots')
    op.drop_column('snapshots', 'worst_status')
    op.drop_column('snapshots', 'is_worst')
    op.drop_column('snapshots', 'signal_result')
    op.drop_column('snapshots', 'cost')
    op.drop_column('snapshots', 'tokens_used')
    op.drop_column('snapshots', 'latency_ms')
    op.drop_column('snapshots', 'response')
    op.drop_column('snapshots', 'user_message')
    op.drop_column('snapshots', 'system_prompt')
    op.drop_column('snapshots', 'model_settings')
    op.drop_column('snapshots', 'is_parallel')
    op.drop_column('snapshots', 'span_order')
    op.drop_column('snapshots', 'parent_span_id')
    op.drop_column('snapshots', 'agent_id')
    op.drop_column('snapshots', 'project_id')
    op.add_column('shared_results', sa.Column('result_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, server_default='{}'))
    op.add_column('shared_results', sa.Column('result_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, server_default='test'))
    op.add_column('shared_results', sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('shared_results', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shared_results', sa.Column('read_only', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('shared_results', sa.Column('result_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shared_results', type_='foreignkey')
    op.create_foreign_key(op.f('shared_results_created_by_fkey'), 'shared_results', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_shared_results_share_token'), table_name='shared_results')
    op.create_index(op.f('ix_shared_results_token'), 'shared_results', ['token'], unique=True)
    op.create_index(op.f('ix_shared_results_result_type'), 'shared_results', ['result_type'], unique=False)
    op.create_index(op.f('ix_shared_results_created_by'), 'shared_results', ['created_by'], unique=False)
    op.create_index(op.f('ix_shared_results_created_at'), 'shared_results', ['created_at'], unique=False)
    op.create_index(op.f('idx_shared_result_token'), 'shared_results', ['token'], unique=False)
    op.create_index(op.f('idx_shared_result_project'), 'shared_results', ['project_id', 'created_at'], unique=False)
    op.alter_column('shared_results', 'id',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('shared_results', 'settings')
    op.drop_column('shared_results', 'is_public')
    op.drop_column('shared_results', 'share_token')
    op.drop_column('shared_results', 'test_run_id')
    op.add_column('rule_market', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('rule_market', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('rule_market', sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('rule_market', sa.Column('pattern_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('rule_market', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('rule_market', sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('rule_market', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('rule_market', sa.Column('pattern', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('rule_market', sa.Column('download_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('rule_market', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('rule_market', sa.Column('rating_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('rule_market_author_id_fkey'), 'rule_market', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_rule_market_rule_type'), 'rule_market', ['rule_type'], unique=False)
    op.create_index(op.f('ix_rule_market_is_featured'), 'rule_market', ['is_featured'], unique=False)
    op.create_index(op.f('ix_rule_market_is_approved'), 'rule_market', ['is_approved'], unique=False)
    op.create_index(op.f('ix_rule_market_featured_approved'), 'rule_market', ['is_featured', 'is_approved'], unique=False)
    op.create_index(op.f('ix_rule_market_created_at'), 'rule_market', ['created_at'], unique=False)
    op.create_index(op.f('ix_rule_market_category_approved'), 'rule_market', ['category', 'is_approved'], unique=False)
    op.create_index(op.f('ix_rule_market_category'), 'rule_market', ['category'], unique=False)
    op.create_index(op.f('ix_rule_market_author_id'), 'rule_market', ['author_id'], unique=False)
    op.alter_column('rule_market', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('rule_market', 'downloads')
    op.drop_column('rule_market', 'author')
    op.drop_column('rule_market', 'config_json')
    op.add_column('quality_scores', sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('quality_scores', sa.Column('coherence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('quality_scores', sa.Column('semantic_consistency_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('quality_scores', sa.Column('tone_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('quality_scores', sa.Column('json_valid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('quality_scores', sa.Column('api_call_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('quality_scores', sa.Column('violations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('quality_scores', sa.Column('format_valid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('quality_scores', sa.Column('evaluation_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('quality_scores', sa.Column('required_fields_present', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('quality_scores', sa.Column('length_acceptable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'quality_scores', type_='foreignkey')
    op.create_foreign_key(op.f('quality_scores_project_id_fkey'), 'quality_scores', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('quality_scores_api_call_id_fkey'), 'quality_scores', 'api_calls', ['api_call_id'], ['id'])
    op.create_index(op.f('ix_quality_scores_api_call_id'), 'quality_scores', ['api_call_id'], unique=False)
    op.drop_column('quality_scores', 'metric_name')
    op.drop_column('quality_scores', 'score')
    op.add_column('public_benchmarks', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('public_benchmarks', sa.Column('benchmark_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('public_benchmarks', sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('public_benchmarks', sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('public_benchmarks', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('public_benchmarks', sa.Column('test_cases_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('public_benchmarks', sa.Column('benchmark_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('public_benchmarks', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('public_benchmarks', sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('public_benchmarks', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('public_benchmarks', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('public_benchmarks_author_id_fkey'), 'public_benchmarks', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_public_benchmarks_is_featured'), 'public_benchmarks', ['is_featured'], unique=False)
    op.create_index(op.f('ix_public_benchmarks_is_approved'), 'public_benchmarks', ['is_approved'], unique=False)
    op.create_index(op.f('ix_public_benchmarks_created_at'), 'public_benchmarks', ['created_at'], unique=False)
    op.create_index(op.f('ix_public_benchmarks_category'), 'public_benchmarks', ['category'], unique=False)
    op.create_index(op.f('ix_public_benchmarks_benchmark_type'), 'public_benchmarks', ['benchmark_type'], unique=False)
    op.create_index(op.f('ix_public_benchmarks_author_id'), 'public_benchmarks', ['author_id'], unique=False)
    op.create_index(op.f('ix_public_benchmark_featured_approved'), 'public_benchmarks', ['is_featured', 'is_approved'], unique=False)
    op.create_index(op.f('ix_public_benchmark_category_approved'), 'public_benchmarks', ['category', 'is_approved'], unique=False)
    op.alter_column('public_benchmarks', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('public_benchmarks', 'data')
    op.drop_column('public_benchmarks', 'version')
    op.add_column('projects', sa.Column('shadow_routing_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.create_index(op.f('idx_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.add_column('project_notification_settings', sa.Column('error_rate_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('project_notification_settings', sa.Column('discord_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('project_notification_settings', sa.Column('min_interval_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('project_notification_settings', sa.Column('slack_webhook_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('project_notification_settings', sa.Column('alert_types', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('project_notification_settings', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('project_notification_settings', sa.Column('quality_score_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('project_notification_settings', sa.Column('drift_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('project_notification_settings', sa.Column('severity_threshold', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('project_notification_settings', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('project_notification_settings', sa.Column('discord_webhook_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('project_notification_settings_user_id_fkey'), 'project_notification_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'project_notification_settings', type_='unique')
    op.create_unique_constraint(op.f('uq_project_notification_settings_project_user'), 'project_notification_settings', ['project_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_project_notification_settings_user_id'), 'project_notification_settings', ['user_id'], unique=False)
    op.create_index(op.f('ix_project_notification_settings_project_id'), 'project_notification_settings', ['project_id'], unique=False)
    op.alter_column('project_notification_settings', 'slack_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('project_notification_settings', 'email_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('project_notification_settings', 'slack_channel')
    op.add_column('pii_patterns', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('pii_patterns', sa.Column('replacement', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pii_patterns', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('pii_patterns_project_id_fkey'), 'pii_patterns', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_pii_patterns_project_id'), 'pii_patterns', ['project_id'], unique=False)
    op.alter_column('pii_patterns', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('pii_patterns', 'entity_type')
    op.drop_index(op.f('ix_organizations_paddle_subscription_id'), table_name='organizations')
    op.create_index(op.f('ix_organizations_paddle_subscription_id'), 'organizations', ['paddle_subscription_id'], unique=True)
    op.drop_index(op.f('ix_organizations_paddle_customer_id'), table_name='organizations')
    op.create_index(op.f('ix_organizations_paddle_customer_id'), 'organizations', ['paddle_customer_id'], unique=True)
    op.create_index(op.f('idx_org_plan'), 'organizations', ['plan_type'], unique=False)
    op.create_index(op.f('idx_org_owner'), 'organizations', ['owner_id'], unique=False)
    op.add_column('organization_members', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('organization_members', sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('organization_members', sa.Column('invited_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('organization_members', sa.Column('invited_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organization_members', type_='foreignkey')
    op.drop_constraint(None, 'organization_members', type_='foreignkey')
    op.create_foreign_key(op.f('organization_members_organization_id_fkey'), 'organization_members', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('organization_members_invited_by_fkey'), 'organization_members', 'users', ['invited_by'], ['id'])
    op.create_foreign_key(op.f('organization_members_user_id_fkey'), 'organization_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_org_user'), 'organization_members', ['organization_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_org_member_role'), 'organization_members', ['organization_id', 'role'], unique=False)
    op.create_index(op.f('idx_org_member'), 'organization_members', ['organization_id', 'user_id'], unique=False)
    op.add_column('notification_settings', sa.Column('in_app_quality_drop', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_settings', sa.Column('in_app_drift', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_settings', sa.Column('discord_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_settings', sa.Column('slack_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_settings', sa.Column('email_drift', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_settings', sa.Column('in_app_cost_anomaly', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_settings', sa.Column('email_cost_anomaly', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_settings', sa.Column('email_quality_drop', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('notification_settings', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notification_settings', type_='foreignkey')
    op.create_foreign_key(op.f('notification_settings_user_id_fkey'), 'notification_settings', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'notification_settings', type_='unique')
    op.create_index(op.f('ix_notification_settings_user_id'), 'notification_settings', ['user_id'], unique=True)
    op.alter_column('notification_settings', 'discord_webhook_url',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('notification_settings', 'slack_webhook_url',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('notification_settings', 'discord_alerts')
    op.drop_column('notification_settings', 'slack_alerts')
    op.drop_column('notification_settings', 'email_alerts')
    op.add_column('judge_feedback', sa.Column('alignment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('judge_feedback', sa.Column('evaluation_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('judge_feedback', sa.Column('correction_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('judge_feedback', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('judge_feedback', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('judge_feedback', sa.Column('human_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('judge_feedback', sa.Column('judge_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'judge_feedback', type_='foreignkey')
    op.drop_constraint(None, 'judge_feedback', type_='foreignkey')
    op.create_foreign_key(op.f('judge_feedback_evaluation_id_fkey'), 'judge_feedback', 'quality_scores', ['evaluation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_judge_feedback_evaluation_id'), 'judge_feedback', ['evaluation_id'], unique=False)
    op.drop_column('judge_feedback', 'metadata_json')
    op.drop_column('judge_feedback', 'rating')
    op.drop_column('judge_feedback', 'judge_id')
    op.drop_column('judge_feedback', 'snapshot_id')
    op.add_column('firewall_rules', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('firewall_rules', sa.Column('pattern_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('firewall_rules', sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('firewall_rules', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('firewall_rules', sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_firewall_rules_created_at'), table_name='firewall_rules')
    op.create_index(op.f('ix_firewall_rules_rule_type'), 'firewall_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_firewall_rules_enabled'), 'firewall_rules', ['enabled'], unique=False)
    op.alter_column('firewall_rules', 'severity',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='firewallseverity'),
               nullable=False)
    op.alter_column('firewall_rules', 'action',
               existing_type=postgresql.ENUM('BLOCK', 'WARN', 'LOG', name='firewallaction'),
               nullable=False)
    op.alter_column('firewall_rules', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('firewall_rules', 'priority')
    op.drop_column('firewall_rules', 'is_active')
    op.add_column('evaluation_rubrics', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('evaluation_rubrics', sa.Column('criteria_prompt', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('evaluation_rubrics', sa.Column('max_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('evaluation_rubrics', sa.Column('min_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_evaluation_rubrics_project_id'), table_name='evaluation_rubrics')
    op.drop_index(op.f('ix_evaluation_rubrics_created_at'), table_name='evaluation_rubrics')
    op.alter_column('evaluation_rubrics', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('drift_detections', sa.Column('baseline_period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('drift_detections', sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('drift_detections', sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('drift_detections', sa.Column('baseline_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('drift_detections', sa.Column('detection_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('drift_detections', sa.Column('affected_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('drift_detections', sa.Column('change_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('drift_detections', sa.Column('current_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('drift_detections', sa.Column('detection_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('drift_detections', sa.Column('agent_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('drift_detections', sa.Column('baseline_period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('drift_detections', sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'drift_detections', type_='foreignkey')
    op.create_foreign_key(op.f('drift_detections_project_id_fkey'), 'drift_detections', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_drift_detections_created_at'), table_name='drift_detections')
    op.create_index(op.f('ix_drift_detections_model'), 'drift_detections', ['model'], unique=False)
    op.create_index(op.f('ix_drift_detections_detection_type'), 'drift_detections', ['detection_type'], unique=False)
    op.create_index(op.f('ix_drift_detections_detected_at'), 'drift_detections', ['detected_at'], unique=False)
    op.create_index(op.f('ix_drift_detections_agent_name'), 'drift_detections', ['agent_name'], unique=False)
    op.drop_column('drift_detections', 'created_at')
    op.drop_column('drift_detections', 'model_name')
    op.add_column('api_calls', sa.Column('response_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('api_calls', sa.Column('request_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('api_calls', sa.Column('request_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('api_calls', sa.Column('response_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('api_calls', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('api_calls', sa.Column('request_prompt', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('api_calls', sa.Column('response_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('api_calls', sa.Column('chain_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'api_calls', type_='foreignkey')
    op.create_foreign_key(op.f('api_calls_project_id_fkey'), 'api_calls', 'projects', ['project_id'], ['id'])
    op.create_index(op.f('ix_api_calls_provider'), 'api_calls', ['provider'], unique=False)
    op.create_index(op.f('ix_api_calls_model'), 'api_calls', ['model'], unique=False)
    op.create_index(op.f('ix_api_calls_chain_id'), 'api_calls', ['chain_id'], unique=False)
    op.create_index(op.f('ix_api_calls_agent_name'), 'api_calls', ['agent_name'], unique=False)
    op.create_index(op.f('idx_provider_model'), 'api_calls', ['provider', 'model'], unique=False)
    op.create_index(op.f('idx_project_created'), 'api_calls', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_chain_id'), 'api_calls', ['chain_id', 'created_at'], unique=False)
    op.alter_column('api_calls', 'latency_ms',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('api_calls', 'model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('api_calls', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('api_calls', 'cost')
    op.drop_column('api_calls', 'total_tokens')
    op.drop_column('api_calls', 'response_content')
    op.drop_column('api_calls', 'request_content')
    op.add_column('alerts', sa.Column('is_sent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('alerts', sa.Column('notification_channels', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('resolved_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('alert_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key(op.f('alerts_resolved_by_fkey'), 'alerts', 'users', ['resolved_by'], ['id'])
    op.create_foreign_key(op.f('alerts_project_id_fkey'), 'alerts', 'projects', ['project_id'], ['id'])
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.drop_column('alerts', 'description')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.create_foreign_key(op.f('activity_logs_project_id_fkey'), 'activity_logs', 'projects', ['project_id'], ['id'])
    op.create_table('shadow_comparisons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('primary_api_call_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('primary_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('shadow_api_call_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shadow_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('similarity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('difference_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('difference_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('difference_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('alert_sent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('alert_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('shadow_comparisons_alert_id_fkey')),
    sa.ForeignKeyConstraint(['primary_api_call_id'], ['api_calls.id'], name=op.f('shadow_comparisons_primary_api_call_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('shadow_comparisons_project_id_fkey')),
    sa.ForeignKeyConstraint(['shadow_api_call_id'], ['api_calls.id'], name=op.f('shadow_comparisons_shadow_api_call_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shadow_comparisons_pkey'))
    )
    op.create_index(op.f('ix_shadow_comparisons_shadow_api_call_id'), 'shadow_comparisons', ['shadow_api_call_id'], unique=False)
    op.create_index(op.f('ix_shadow_comparisons_project_id'), 'shadow_comparisons', ['project_id'], unique=False)
    op.create_index(op.f('ix_shadow_comparisons_primary_api_call_id'), 'shadow_comparisons', ['primary_api_call_id'], unique=False)
    op.create_index(op.f('ix_shadow_comparisons_id'), 'shadow_comparisons', ['id'], unique=False)
    op.create_index(op.f('ix_shadow_comparisons_created_at'), 'shadow_comparisons', ['created_at'], unique=False)
    op.drop_index(op.f('ix_test_results_test_run_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_project_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_created_at'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_agent_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_signal_detections_snapshot_id'), table_name='signal_detections')
    op.drop_index(op.f('ix_signal_detections_signal_type'), table_name='signal_detections')
    op.drop_index(op.f('ix_signal_detections_project_id'), table_name='signal_detections')
    op.drop_index(op.f('ix_signal_detections_id'), table_name='signal_detections')
    op.drop_index(op.f('ix_signal_detections_created_at'), table_name='signal_detections')
    op.drop_table('signal_detections')
    op.drop_index(op.f('ix_test_runs_project_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_created_at'), table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index(op.f('ix_test_lab_canvases_project_id'), table_name='test_lab_canvases')
    op.drop_index(op.f('ix_test_lab_canvases_id'), table_name='test_lab_canvases')
    op.drop_index(op.f('ix_test_lab_canvases_created_at'), table_name='test_lab_canvases')
    op.drop_table('test_lab_canvases')
    op.drop_index(op.f('ix_signal_configs_project_id'), table_name='signal_configs')
    op.drop_index(op.f('ix_signal_configs_id'), table_name='signal_configs')
    op.drop_index(op.f('ix_signal_configs_created_at'), table_name='signal_configs')
    op.drop_table('signal_configs')
    op.drop_index(op.f('ix_replay_runs_project_id'), table_name='replay_runs')
    op.drop_index(op.f('ix_replay_runs_id'), table_name='replay_runs')
    op.drop_table('replay_runs')
    op.drop_index(op.f('ix_live_view_connections_project_id'), table_name='live_view_connections')
    op.drop_index(op.f('ix_live_view_connections_id'), table_name='live_view_connections')
    op.drop_index(op.f('ix_live_view_connections_created_at'), table_name='live_view_connections')
    op.drop_table('live_view_connections')
    op.drop_index(op.f('ix_agent_display_settings_project_id'), table_name='agent_display_settings')
    op.drop_index(op.f('ix_agent_display_settings_id'), table_name='agent_display_settings')
    op.drop_index(op.f('ix_agent_display_settings_created_at'), table_name='agent_display_settings')
    op.drop_table('agent_display_settings')
    # ### end Alembic commands ###
