"""sync_schema_to_models

Revision ID: 7e6b6a17ec5b
Revises: 5e5a8559f4d4
Create Date: 2026-02-18 00:56:44.716176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6b6a17ec5b'
down_revision = '5e5a8559f4d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)

    agent_display_settings_cols = {col["name"] for col in insp.get_columns("agent_display_settings")}
    if "diagnostic_config" not in agent_display_settings_cols:
        op.add_column('agent_display_settings', sa.Column('diagnostic_config', sa.JSON(), server_default='{}', nullable=True))

    organizations_cols = {col["name"] for col in insp.get_columns("organizations")}
    if "type" not in organizations_cols:
        op.add_column('organizations', sa.Column('type', sa.String(length=50), nullable=True))
    if "paddle_customer_id" not in organizations_cols:
        op.add_column('organizations', sa.Column('paddle_customer_id', sa.String(length=255), nullable=True))
    if "paddle_subscription_id" not in organizations_cols:
        op.add_column('organizations', sa.Column('paddle_subscription_id', sa.String(length=255), nullable=True))

    projects_cols = {col["name"] for col in insp.get_columns("projects")}
    if "canvas_nodes" not in projects_cols:
        op.add_column('projects', sa.Column('canvas_nodes', sa.JSON(), nullable=True))
    if "canvas_edges" not in projects_cols:
        op.add_column('projects', sa.Column('canvas_edges', sa.JSON(), nullable=True))
    if "diagnostic_config" not in projects_cols:
        op.add_column('projects', sa.Column('diagnostic_config', sa.JSON(), server_default='{}', nullable=True))

    snapshots_cols = {col["name"] for col in insp.get_columns("snapshots")}
    if "evaluation_result" not in snapshots_cols:
        op.add_column('snapshots', sa.Column('evaluation_result', sa.JSON(), nullable=True))
    if "is_golden" not in snapshots_cols:
        op.add_column('snapshots', sa.Column('is_golden', sa.Boolean(), server_default='false', nullable=True))

    test_results_cols = {col["name"] for col in insp.get_columns("test_results")}
    if "is_golden" not in test_results_cols:
        op.add_column('test_results', sa.Column('is_golden', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)

    test_results_cols = {col["name"] for col in insp.get_columns("test_results")}
    if "is_golden" in test_results_cols:
        op.drop_column('test_results', 'is_golden')

    snapshots_cols = {col["name"] for col in insp.get_columns("snapshots")}
    if "is_golden" in snapshots_cols:
        op.drop_column('snapshots', 'is_golden')
    if "evaluation_result" in snapshots_cols:
        op.drop_column('snapshots', 'evaluation_result')

    projects_cols = {col["name"] for col in insp.get_columns("projects")}
    if "diagnostic_config" in projects_cols:
        op.drop_column('projects', 'diagnostic_config')
    if "canvas_edges" in projects_cols:
        op.drop_column('projects', 'canvas_edges')
    if "canvas_nodes" in projects_cols:
        op.drop_column('projects', 'canvas_nodes')

    organizations_cols = {col["name"] for col in insp.get_columns("organizations")}
    if "paddle_subscription_id" in organizations_cols:
        op.drop_column('organizations', 'paddle_subscription_id')
    if "paddle_customer_id" in organizations_cols:
        op.drop_column('organizations', 'paddle_customer_id')
    if "type" in organizations_cols:
        op.drop_column('organizations', 'type')

    agent_display_settings_cols = {col["name"] for col in insp.get_columns("agent_display_settings")}
    if "diagnostic_config" in agent_display_settings_cols:
        op.drop_column('agent_display_settings', 'diagnostic_config')
    # ### end Alembic commands ###
