"""sync_schema_to_models

Revision ID: 7e6b6a17ec5b
Revises: 5e5a8559f4d4
Create Date: 2026-02-18 00:56:44.716176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6b6a17ec5b'
down_revision = '5e5a8559f4d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_display_settings', sa.Column('diagnostic_config', sa.JSON(), server_default='{}', nullable=True))
    op.add_column('organizations', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('paddle_customer_id', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('paddle_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('canvas_nodes', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('canvas_edges', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('diagnostic_config', sa.JSON(), server_default='{}', nullable=True))
    op.add_column('snapshots', sa.Column('evaluation_result', sa.JSON(), nullable=True))
    op.add_column('snapshots', sa.Column('is_golden', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('test_results', sa.Column('is_golden', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_results', 'is_golden')
    op.drop_column('snapshots', 'is_golden')
    op.drop_column('snapshots', 'evaluation_result')
    op.drop_column('projects', 'diagnostic_config')
    op.drop_column('projects', 'canvas_edges')
    op.drop_column('projects', 'canvas_nodes')
    op.drop_column('organizations', 'paddle_subscription_id')
    op.drop_column('organizations', 'paddle_customer_id')
    op.drop_column('organizations', 'type')
    op.drop_column('agent_display_settings', 'diagnostic_config')
    # ### end Alembic commands ###
